# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s31f6:
      dhcp4: no
      dhcp6: yes
      addresses: 
          [192.168.2.111/24]
      gateway4: 
          192.168.2.1
      nameservers: 
          addresses: 
              [1.1.1.1,8.8.8.8,8.8.4.4]
